# https://cloud.google.com/appengine/docs/standard/python3/runtime#python-3.8
runtime: python38
instance_class: F1

# entrypoint is not neccesary because search for main.py in root with object app 
entrypoint: gunicorn -b:$PORT falken_quotes.main:app 
# No incluyas gunicorn en requirements.txt, a menos que especifiques el entrypoint

env_variables:
  FALKEN_VERSION: "1.0.0"
  ENV_PRO: "Y"
  LEVEL_LOG: ["INFO", "WARNING", "ERROR"]
  API_URL_QUOTES: "https://zenquotes.io/api/random"
  API_URL_TRANSLATE: "https://nlp-translation.p.rapidapi.com/v1/translate"
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

includes:
- credentials.yaml